### PR TITLE
libretro: Remove the need for Bootstrap class and auto-locate java

### PR DESCRIPTION
**Pull request by phcoder**
Couldn't test with latest version due to https://github.com/msx80/Omicron/issues/5

While on it fix crash on missing JVM and couple of warnings

### CODE REVIEW

**Comment by msx80** [comment]
Hi there, thank you so much for you interest in Omicron! I'll review your changes asap, at first site it looks ok!
Note that i'm a little late with commits, i have some work in local that i've yet to commit, fortunately doesn't seem to be clashing with your changes. I'll do it asap.

**Comment by phcoder** [comment]
With your hint on how to build .jar, I was able to test it and it worked

**Comment by msx80** [comment]
Thank you! On what OS have you tested ?

**Comment by phcoder** [comment]
> Thank you! On what OS have you tested ?

Debian

**Pull request merged**
